// Automatically generated by MockGen. DO NOT EDIT!
// Source: src/github.com/mozilla-services/pushgo/simplepush/server.go

package simplepush

import (
	time "time"
	gomock "github.com/rafrombrc/gomock/gomock"
)

// Mock of Server interface
type MockServer struct {
	ctrl     *gomock.Controller
	recorder *_MockServerRecorder
}

// Recorder for MockServer (not exported)
type _MockServerRecorder struct {
	mock *MockServer
}

func NewMockServer(ctrl *gomock.Controller) *MockServer {
	mock := &MockServer{ctrl: ctrl}
	mock.recorder = &_MockServerRecorder{mock}
	return mock
}

func (_m *MockServer) EXPECT() *_MockServerRecorder {
	return _m.recorder
}

func (_m *MockServer) RequestFlush(worker Worker, chid string, vers int64, data string) error {
	ret := _m.ctrl.Call(_m, "RequestFlush", worker, chid, vers, data)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockServerRecorder) RequestFlush(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RequestFlush", arg0, arg1, arg2, arg3)
}

func (_m *MockServer) UpdateWorker(worker Worker, chid string, vers int64, sentAt time.Time, data string) error {
	ret := _m.ctrl.Call(_m, "UpdateWorker", worker, chid, vers, sentAt, data)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockServerRecorder) UpdateWorker(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "UpdateWorker", arg0, arg1, arg2, arg3, arg4)
}

func (_m *MockServer) Hello(worker Worker, connect []byte) error {
	ret := _m.ctrl.Call(_m, "Hello", worker, connect)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockServerRecorder) Hello(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Hello", arg0, arg1)
}

func (_m *MockServer) Regis(worker Worker, chid string) (string, error) {
	ret := _m.ctrl.Call(_m, "Regis", worker, chid)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockServerRecorder) Regis(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Regis", arg0, arg1)
}

func (_m *MockServer) Bye(worker Worker) error {
	ret := _m.ctrl.Call(_m, "Bye", worker)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockServerRecorder) Bye(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Bye", arg0)
}
