// Automatically generated by MockGen. DO NOT EDIT!
// Source: src/github.com/mozilla-services/pushgo/simplepush/metrics.go

package simplepush

import (
	gomock "github.com/rafrombrc/gomock/gomock"
	time "time"
)

// Mock of Statistician interface
type MockStatistician struct {
	ctrl     *gomock.Controller
	recorder *_MockStatisticianRecorder
}

// Recorder for MockStatistician (not exported)
type _MockStatisticianRecorder struct {
	mock *MockStatistician
}

func NewMockStatistician(ctrl *gomock.Controller) *MockStatistician {
	mock := &MockStatistician{ctrl: ctrl}
	mock.recorder = &_MockStatisticianRecorder{mock}
	return mock
}

func (_m *MockStatistician) EXPECT() *_MockStatisticianRecorder {
	return _m.recorder
}

func (_m *MockStatistician) Init(_param0 *Application, _param1 interface{}) error {
	ret := _m.ctrl.Call(_m, "Init", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockStatisticianRecorder) Init(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Init", arg0, arg1)
}

func (_m *MockStatistician) Prefix(_param0 string) {
	_m.ctrl.Call(_m, "Prefix", _param0)
}

func (_mr *_MockStatisticianRecorder) Prefix(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Prefix", arg0)
}

func (_m *MockStatistician) Snapshot() map[string]interface{} {
	ret := _m.ctrl.Call(_m, "Snapshot")
	ret0, _ := ret[0].(map[string]interface{})
	return ret0
}

func (_mr *_MockStatisticianRecorder) Snapshot() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Snapshot")
}

func (_m *MockStatistician) IncrementBy(_param0 string, _param1 int64) {
	_m.ctrl.Call(_m, "IncrementBy", _param0, _param1)
}

func (_mr *_MockStatisticianRecorder) IncrementBy(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "IncrementBy", arg0, arg1)
}

func (_m *MockStatistician) Increment(_param0 string) {
	_m.ctrl.Call(_m, "Increment", _param0)
}

func (_mr *_MockStatisticianRecorder) Increment(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Increment", arg0)
}

func (_m *MockStatistician) Decrement(_param0 string) {
	_m.ctrl.Call(_m, "Decrement", _param0)
}

func (_mr *_MockStatisticianRecorder) Decrement(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Decrement", arg0)
}

func (_m *MockStatistician) Timer(_param0 string, _param1 time.Duration) {
	_m.ctrl.Call(_m, "Timer", _param0, _param1)
}

func (_mr *_MockStatisticianRecorder) Timer(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Timer", arg0, arg1)
}

func (_m *MockStatistician) Gauge(_param0 string, _param1 int64) {
	_m.ctrl.Call(_m, "Gauge", _param0, _param1)
}

func (_mr *_MockStatisticianRecorder) Gauge(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Gauge", arg0, arg1)
}

func (_m *MockStatistician) GaugeDelta(_param0 string, _param1 int64) {
	_m.ctrl.Call(_m, "GaugeDelta", _param0, _param1)
}

func (_mr *_MockStatisticianRecorder) GaugeDelta(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GaugeDelta", arg0, arg1)
}
