#! /bin/bash
if [ ! -e config.ini ]; then
    echo "Copying sample ini to config.ini"
    cp config.sample.ini config.ini
fi
GOPATH="$(pwd)/Godeps/_workspace:$(pwd):$GOPATH" go build github.com/mozilla-services/pushgo
GOPATH="$(pwd)/Godeps/_workspace:$(pwd):$GOPATH" ./pushgo $*
