#! /bin/bash
if [ ! -e config.ini ]; then
    echo "Copying sample ini to config.ini"
    cp config.sample.ini config.ini
fi
GOPATH="$(pwd):$GOPATH" go build simplepush.go
GOPATH="$(pwd):$GOPATH" ./simplepush $*
